---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/why
  label: Why
  create: all
  match: "**/*"
- type: directory
  path: content/support
  label: Support
  create: all
  match: "**/*"
- type: directory
  path: content/quickstart
  label: Quickstart
  create: all
  match: "**/*"
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*"
- type: directory
  path: content/nfhack
  label: Nfhack
  create: all
  match: "**/*"
- type: directory
  path: content/nfcamp
  label: Nfcamp
  create: all
  match: "**/*"
- type: directory
  path: content/learn
  label: Learn
  create: all
  match: "**/*"
- type: directory
  path: content/home
  label: Home
  create: all
  match: "**/*"
- type: directory
  path: content/events
  label: Events
  create: all
  match: "**/*"
- type: directory
  path: content/docs
  label: Docs
  create: all
  match: "**/*"
- type: directory
  path: content/community
  label: Community
  create: all
  match: "**/*"
- type: directory
  path: content/authors
  label: Authors
  create: all
  match: "**/*"
- type: directory
  path: content/about
  label: About
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.76.5
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.76.5
